/*
 * continuation.h:
 * This file is automatically generated; please do not edit it.
 */

#include <et/com_err.h>

#define CHPASS_UTIL_PASSWORD_IN_DICTIONARY       (156463126912L)
extern const struct error_table et_kadm5_error_table;
extern void initialize_kadm5_error_table(void);
#define ERROR_TABLE_BASE_kadm5 (156463126912L)

/* for compatibility with older versions... */
#define init_kadm5_err_tbl initialize_kadm5_error_table
#define kadm5_err_base ERROR_TABLE_BASE_kadm5
