/*
 * continuation.c:
 * This file is automatically generated; please do not edit it.
 */

static const char * const text[] = {
	"New password was found in a dictionary of possible passwords and\ntherefore may be easily guessed. Please choose another password.\nSee the ovpasswd man page for help in choosing a good password.",
    0
};

struct error_table {
    char const * const * msgs;
    long base;
    int n_msgs;
};
struct et_list {
    struct et_list *next;
    const struct error_table * table;
};
extern struct et_list *_et_list;

const struct error_table et_kadm5_error_table = { text, 156463126912L, 1 };

static struct et_list link = { 0, 0 };

void initialize_kadm5_error_table(void);

void initialize_kadm5_error_table(void) {
    if (!link.table) {
        link.next = _et_list;
        link.table = &et_kadm5_error_table;
        _et_list = &link;
    }
}
