/*
 * simple.c:
 * This file is automatically generated; please do not edit it.
 */

static const char * const text[] = {
				"Can't read ticket file",
				"Can't find ticket or TGT",
				"TGT expired",
				"Can't decode authenticator",
				"Ticket expired",
				"Repeated request",
				"The ticket isn't for us",
				"Request is inconsistent",
				"Delta-T too big",
				"Incorrect net address",
				"Protocol version mismatch",
				"Invalid message type",
				"Message stream modified",
				"Message out of order",
				"Unauthorized request",
				"Current password is null",
				"Incorrect current password",
				"Protocol error",
				"Error returned by KDC",
				"Null ticket returned by KDC",
				"Retry count exceeded",
				"Can't send request",
    0
};

struct error_table {
    char const * const * msgs;
    long base;
    int n_msgs;
};
struct et_list {
    struct et_list *next;
    const struct error_table * table;
};
extern struct et_list *_et_list;

const struct error_table et_krb_error_table = { text, 39525376L, 22 };

static struct et_list link = { 0, 0 };

void initialize_krb_error_table(void);

void initialize_krb_error_table(void) {
    if (!link.table) {
        link.next = _et_list;
        link.table = &et_krb_error_table;
        _et_list = &link;
    }
}
