all:: $(LIBRARY)_chk.a

real-subdirs:: Makefile
	@echo "	MKDIR checker"
	@mkdir -p checker

clean::
	$(RM) -rf checker

$(LIBRARY)_chk.a: $(OBJS)
	@echo "	GEN_CHECKER_LIB $@"
	@(test -r $@ && $(RM) -f $@.bak && $(MV) $@ $@.bak)
	(cd checker; $(ARGEN) $@ $(OBJS))
	-@$(RANLIB) $@
	@$(RM) -f ../$@
	@$(LN) $@ ../$@
