<Center>
<H1> Welcome to the E2fsprogs Sourceforge Page</H1>
</CENTER>

<P>This is the home page for the e2fsprogs package.  It provides the
filesystem utilities for use with the <A HREF="ext2.html">ext2
filesystem.</A> It also supports the ext3 filesystem with journaling
support.</P>

<P>The e2fsprogs <A HREF="http://sourceforge.net/projects/e2fsprogs">
Sourceforge summary page</A> can be found here.  For more information
about the ext2 filesystem, <A HREF="ext2.html">click here</A>.</P>

<P>The latest development sources for e2fsprogs is maintained in a <A
HREF="http://www.kernel.org/pub/software/scm/git/docs">Git</A>
repository at <a
HREF="http://git.kernel.org/?p=fs/ext2/e2fsprogs.git;a=summary">git://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git</a>.
A quick tutorial about how to start using git can be found 
<A HREF="http://www.kernel.org/pub/software/scm/git/docs/tutorial.html">here</A>.</P>


<IMG SRC="images/new.gif" ALIGN=LEFT><H2>Release 1.40.4 of e2fsprogs is
available!</H2>

<P>I am happy to announce a new release of the e2fsprogs distribution.
All users of e2fsprogs are urged to upgrade to the 1.40.4 version as
soon as possible, which can be found <A HREF="http://prdownloads.sourceforge.net/e2fsprogs/e2fsprogs-1.40.4.tar.gz">here</A>.</P>

<P>This release contains a number of bug fixes and enhancements over
the previous releases.  In particular if you wish to experiment with
the on-line resizing feature in the 2.6 kernels you should upgrade to
this version of e2fsprogs.  For more details, see the 
<A HREF="e2fsprogs-release.html">release notes.</A></P>


<ADDRESS>
<A HREF="http://thunk.org/tytso">Theodore Ts'o</A>
</ADDRESS> 


